//! omega-metacog: Reflective agent for autonomous insight generation.
//!
//! The metacog layer analyzes the MemoryGraph to identify patterns, drifts, and
//! opportunities for cognitive optimization.

#![warn(missing_docs)]

pub mod dream;

use omega_core::now;
use omega_myelin::MemoryGraph;
use serde::{Deserialize, Serialize};

/// Epiphany: A synthetic policy update generated by the metacog agent.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Epiphany {
    /// Human-readable description of the insight
    pub insight: String,
    /// IDs of memory nodes that triggered this epiphany
    pub supporting_nodes: Vec<String>,
    /// Confidence score [0.0, 1.0]
    pub confidence: f64,
    /// Category of insight
    pub category: EpiphanyCategory,
    /// Unix timestamp
    pub timestamp: f64,
}

/// Categories of insight the metacog agent can generate
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum EpiphanyCategory {
    /// A concept is accessed frequently and should be promoted in retrieval priority
    HotNode,
    /// A concept's decay score has dropped below relevance threshold — prune candidate
    ColdNode,
    /// Threat pattern appears repeatedly — escalate to AEGIS
    ThreatEscalation,
    /// Multiple related nodes are accessed together — suggests a cluster that could be merged
    ClusterCandidate,
    /// A node has never been retrieved despite high connectivity — orphaned knowledge
    OrphanedKnowledge,
    /// Recent retrieval rate has spiked — possible topic shift in operator focus
    TopicShift,
}

/// MetacogAgent: Performs reflective analysis on the MemoryGraph.
pub struct MetacogAgent {
    /// Epiphanies generated across all reflection cycles
    pub history: Vec<Epiphany>,
    /// Minimum retrieval count to qualify as a HotNode
    hot_threshold: u64,
    /// Maximum decay score before a node is considered Cold
    cold_threshold: f64,
    /// Minimum decay score for a node to be considered active
    active_floor: f64,
}

impl MetacogAgent {
    /// Initialize a new agent with default thresholds
    pub fn new() -> Self {
        Self {
            history: Vec::new(),
            hot_threshold: 5,
            cold_threshold: 0.15,
            active_floor: 0.05,
        }
    }

    /// Perform a full reflection cycle on the given memory graph.
    ///
    /// Runs six analysis passes:
    /// 1. Hot node detection (high retrieval, low decay — stabilize)
    /// 2. Cold node detection (very low decay — prune candidates)
    /// 3. Threat pattern escalation (repeated threat nodes)
    /// 4. Cluster detection (nodes accessed together)
    /// 5. Orphaned knowledge (connected but never retrieved)
    /// 6. Topic shift detection (sudden retrieval spike)
    pub fn reflect(&mut self, graph: &MemoryGraph) -> Vec<Epiphany> {
        let mut new_insights: Vec<Epiphany> = Vec::new();

        // Pass 1: Hot nodes — high retrieval + low decay = priority stabilization target
        for (id, node) in &graph.nodes {
            if node.retrieval_count >= self.hot_threshold && node.decay_score < 0.3 {
                new_insights.push(Epiphany {
                    insight: format!(
                        "Hot cognitive focus on '{}' ({} retrievals, decay={:.2}). \
                        Promote retrieval priority and consider consolidating related nodes.",
                        &node.content[..node.content.len().min(60)],
                        node.retrieval_count,
                        node.decay_score,
                    ),
                    supporting_nodes: vec![id.clone()],
                    confidence: 0.85 + (node.retrieval_count as f64 * 0.01).min(0.14),
                    category: EpiphanyCategory::HotNode,
                    timestamp: now(),
                });
            }
        }

        // Pass 2: Cold nodes — decay below floor = prune candidates
        for (id, node) in &graph.nodes {
            if node.decay_score < self.cold_threshold && node.retrieval_count == 0 {
                new_insights.push(Epiphany {
                    insight: format!(
                        "Cold node '{}' has never been retrieved and has decayed to {:.3}. \
                        Candidate for pruning or archival.",
                        &node.content[..node.content.len().min(60)],
                        node.decay_score,
                    ),
                    supporting_nodes: vec![id.clone()],
                    confidence: 0.75,
                    category: EpiphanyCategory::ColdNode,
                    timestamp: now(),
                });
            }
        }

        // Pass 3: Threat escalation — nodes whose content contains threat keywords,
        // surfaced repeatedly via threat_fabric entries in the graph.
        let threat_count = graph.threat_fabric.len();
        if threat_count >= 3 {
            let ids: Vec<String> = graph
                .threat_fabric
                .iter()
                .map(|t| t.pattern_id.clone())
                .collect();
            let top_entry = graph
                .threat_fabric
                .iter()
                .max_by_key(|t| t.severity.as_str());
            let top_label = top_entry
                .and_then(|t| t.labels.first())
                .map(|s| s.as_str())
                .unwrap_or("unknown");
            new_insights.push(Epiphany {
                insight: format!(
                    "{} threat patterns in memory fabric (highest severity label: '{}').\
                    Escalating to AEGIS for policy hardening.",
                    threat_count,
                    &top_label[..top_label.len().min(60)],
                ),
                supporting_nodes: ids,
                confidence: 0.92,
                category: EpiphanyCategory::ThreatEscalation,
                timestamp: now(),
            });
        }

        // Pass 4: Cluster detection — nodes accessed in the same retrieval episodes
        // form implicit clusters. Find recurring co-access pairs.
        let mut co_access: std::collections::HashMap<String, Vec<String>> =
            std::collections::HashMap::new();
        for episode in &graph.episodes {
            for node_id in &episode.result_nodes {
                co_access.entry(node_id.clone()).or_default().extend(
                    episode
                        .result_nodes
                        .iter()
                        .filter(|n| *n != node_id)
                        .cloned(),
                );
            }
        }
        for (anchor, co_nodes) in &co_access {
            // deduplicate
            let mut unique_co: Vec<String> = co_nodes.clone();
            unique_co.sort();
            unique_co.dedup();
            if unique_co.len() >= 3 {
                let mut cluster_ids = unique_co.clone();
                cluster_ids.push(anchor.clone());
                new_insights.push(Epiphany {
                    insight: format!(
                        "Node '{}' is consistently co-accessed with {} other nodes — \
                        cluster candidate. Consider consolidating into a semantic group.",
                        anchor,
                        unique_co.len(),
                    ),
                    supporting_nodes: cluster_ids,
                    confidence: 0.70,
                    category: EpiphanyCategory::ClusterCandidate,
                    timestamp: now(),
                });
            }
        }

        // Pass 5: Orphaned knowledge — nodes with edges but zero retrievals
        let connected_ids: std::collections::HashSet<String> = graph
            .edges
            .iter()
            .flat_map(|e| [e.from_id.clone(), e.to_id.clone()])
            .collect();
        for (id, node) in &graph.nodes {
            if connected_ids.contains(id)
                && node.retrieval_count == 0
                && node.decay_score > self.active_floor
            {
                new_insights.push(Epiphany {
                    insight: format!(
                        "Node '{}' is connected to {} other nodes but has never been retrieved. \
                        Potential orphaned knowledge — review for relevance.",
                        &node.content[..node.content.len().min(60)],
                        graph
                            .edges
                            .iter()
                            .filter(|e| &e.from_id == id || &e.to_id == id)
                            .count(),
                    ),
                    supporting_nodes: vec![id.clone()],
                    confidence: 0.65,
                    category: EpiphanyCategory::OrphanedKnowledge,
                    timestamp: now(),
                });
            }
        }

        // Pass 6: Topic shift — retrieval rate spike in recent history
        if graph.episodes.len() >= 2 {
            let recent = &graph.episodes[graph.episodes.len().saturating_sub(5)..];
            let older = &graph.episodes[..graph.episodes.len().saturating_sub(5)];
            if !older.is_empty() {
                let recent_avg = recent.iter().map(|e| e.result_nodes.len()).sum::<usize>() as f64
                    / recent.len() as f64;
                let older_avg = older.iter().map(|e| e.result_nodes.len()).sum::<usize>() as f64
                    / older.len() as f64;
                if recent_avg > older_avg * 2.0 && older_avg > 0.0 {
                    new_insights.push(Epiphany {
                        insight: format!(
                            "Retrieval rate spiked {:.1}x over baseline ({:.1} vs {:.1} nodes/episode). \
                            Possible topic shift in operator focus — consider pre-warming related nodes.",
                            recent_avg / older_avg, recent_avg, older_avg,
                        ),
                        supporting_nodes: vec![],
                        confidence: 0.78,
                        category: EpiphanyCategory::TopicShift,
                        timestamp: now(),
                    });
                }
            }
        }

        self.history.extend(new_insights.clone());
        new_insights
    }

    /// Return all epiphanies of a given category from history
    pub fn epiphanies_by_category(&self, category: &EpiphanyCategory) -> Vec<&Epiphany> {
        self.history
            .iter()
            .filter(|e| &e.category == category)
            .collect()
    }

    /// Return the highest-confidence epiphany from the last reflection
    pub fn top_insight(&self) -> Option<&Epiphany> {
        self.history
            .iter()
            .max_by(|a, b| a.confidence.partial_cmp(&b.confidence).unwrap())
    }

    /// Return threat escalations that should be forwarded to AEGIS
    pub fn pending_threat_escalations(&self) -> Vec<&Epiphany> {
        self.epiphanies_by_category(&EpiphanyCategory::ThreatEscalation)
    }
}

impl Default for MetacogAgent {
    fn default() -> Self {
        Self::new()
    }
}

/// MetacogAgent: Validation logic for context radius.
impl MetacogAgent {
    /// Validate an expanded retrieval context and prune empty episodes.
    pub fn validate_context_radius(
        &self,
        expanded_context: &[omega_core::RetrievalEpisode],
    ) -> Vec<omega_core::RetrievalEpisode> {
        // Prune irrelevant nodes: keep only episodes with high causal link density.
        expanded_context
            .iter()
            .filter(|e| !e.result_nodes.is_empty())
            .cloned()
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use omega_core::{MemoryEdge, MemoryNode, RetrievalEpisode};
    use omega_myelin::{MemoryGraph, ThreatEntry};

    fn hot_node(id: &str) -> MemoryNode {
        MemoryNode {
            node_id: id.into(),
            content: format!("Hot content for {}", id),
            retrieval_count: 10,
            decay_score: 0.2,
        }
    }

    fn cold_node(id: &str) -> MemoryNode {
        MemoryNode {
            node_id: id.into(),
            content: format!("Cold content for {}", id),
            retrieval_count: 0,
            decay_score: 0.05,
        }
    }

    fn connected_orphan(id: &str) -> MemoryNode {
        MemoryNode {
            node_id: id.into(),
            content: format!("Orphaned content for {}", id),
            retrieval_count: 0,
            decay_score: 0.5,
        }
    }

    #[test]
    fn test_hot_node_detection() {
        let mut agent = MetacogAgent::new();
        let mut graph = MemoryGraph::new();
        graph.add_node(hot_node("h1"));
        let insights = agent.reflect(&graph);
        assert!(insights.iter().any(|e| e.category == EpiphanyCategory::HotNode));
    }

    #[test]
    fn test_cold_node_detection() {
        let mut agent = MetacogAgent::new();
        let mut graph = MemoryGraph::new();
        graph.add_node(cold_node("c1"));
        let insights = agent.reflect(&graph);
        assert!(insights.iter().any(|e| e.category == EpiphanyCategory::ColdNode));
    }

    #[test]
    fn test_threat_escalation() {
        let mut agent = MetacogAgent::new();
        let mut graph = MemoryGraph::new();
        for i in 0..4 {
            graph.threat_fabric.push(ThreatEntry {
                pattern_id: format!("p-{}", i),
                severity: "high".into(),
                labels: vec!["JAILBREAK".into()],
            });
        }
        let insights = agent.reflect(&graph);
        assert!(insights.iter().any(|e| e.category == EpiphanyCategory::ThreatEscalation));
    }

    #[test]
    fn test_orphaned_knowledge_detection() {
        let mut agent = MetacogAgent::new();
        let mut graph = MemoryGraph::new();
        let node = connected_orphan("o1");
        graph.add_node(node);
        graph.add_node(connected_orphan("o2"));
        graph.edges.push(MemoryEdge {
            from: "o1".into(),
            to: "o2".into(),
            from_id: "o1".into(),
            to_id: "o2".into(),
        });
        let insights = agent.reflect(&graph);
        assert!(insights.iter().any(|e| e.category == EpiphanyCategory::OrphanedKnowledge));
    }

    #[test]
    fn test_epiphanies_by_category() {
        let mut agent = MetacogAgent::new();
        let mut graph = MemoryGraph::new();
        graph.add_node(hot_node("h1"));
        graph.add_node(cold_node("c1"));
        agent.reflect(&graph);
        let hot = agent.epiphanies_by_category(&EpiphanyCategory::HotNode);
        assert!(!hot.is_empty());
    }

    #[test]
    fn test_top_insight() {
        let mut agent = MetacogAgent::new();
        let mut graph = MemoryGraph::new();
        graph.add_node(hot_node("h1"));
        agent.reflect(&graph);
        assert!(agent.top_insight().is_some());
    }

    #[test]
    fn test_validate_context_radius_prunes_empty() {
        let agent = MetacogAgent::new();
        let episodes = vec![
            RetrievalEpisode {
                episode_id: "e1".into(),
                content: "test".into(),
                result_nodes: vec!["n1".into()],
            },
            RetrievalEpisode {
                episode_id: "e2".into(),
                content: "empty".into(),
                result_nodes: vec![],
            },
        ];
        let pruned = agent.validate_context_radius(&episodes);
        assert_eq!(pruned.len(), 1);
        assert_eq!(pruned[0].episode_id, "e1");
    }
}

