// omega-metacog: Reflective agent for autonomous insight generation.
// The metacog layer analyzes the MemoryGraph to identify patterns, 
// drifts, and opportunities for cognitive optimization.

#![warn(missing_docs)]

pub mod dream;

use omega_core::now;
use omega_myelin::MemoryGraph;
use serde::{Deserialize, Serialize};

/// Epiphany: A synthetic policy update generated by the metacog agent.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Epiphany {
    /// Description of the insight
    pub insight: String,
    /// Memory nodes that triggered this
    pub supporting_nodes: Vec<String>,
    /// Confidence in the insight
    pub confidence: f64,
    /// Timestamp
    pub timestamp: f64,
}

/// MetacogAgent: Analyzes memory for insights.
pub struct MetacogAgent {
    /// Epiphanies generated
    pub history: Vec<Epiphany>,
}

impl MetacogAgent {
    /// Initialize a new agent
    pub fn new() -> Self {
        Self { history: Vec::new() }
    }

    /// Perform a reflection cycle on the memory graph.
    pub fn reflect(&mut self, graph: &MemoryGraph) -> Vec<Epiphany> {
        let mut new_insights = Vec::new();

        // Autonomous analysis: identify nodes with high retrieval but low decay score
        // (This indicates a "hot" area of interest that needs stabilization).
        for (id, node) in &graph.nodes {
            if node.retrieval_count > 5 && node.decay_score < 0.3 {
                new_insights.push(Epiphany {
                    insight: format!("Stabilizing cognitive focus on: {}", node.content),
                    supporting_nodes: vec![id.to_string()],
                    confidence: 0.85,
                    timestamp: now(),
                });
            }
        }

        self.history.extend(new_insights.clone());
        new_insights
    }
}
